name       : ksmtp
version    : 23.04.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/ksmtp-23.04.3.tar.xz : 22c011f810015a114887892aff3829b0a111d20ab1a55606edc2a261eb3ee15f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
