name       : ksmtp
version    : 20.08.2
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/ksmtp-20.08.2.tar.xz : 5f51e0c025b192719709ae763feeac94df893007b62b5a69b7b95ae9f2fdd8ee
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
