name       : ksmtp
version    : 21.08.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/ksmtp-21.08.3.tar.xz : a060b93620a673d05578ffd93b8faa5b003e5069723fc490e7f3b3877e003f36
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
