name       : ksmtp
version    : 20.08.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/ksmtp-20.08.3.tar.xz : cc2b45e7a686c6116d91a2e849ab40739dd2f1077ae8cd6574a27a5df7a72cdd
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
