name       : ksmtp
version    : 21.12.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/ksmtp-21.12.0.tar.xz : 2cda0ac5a355e2828770fb34e5684a01db306918a9fe748a897471bf3552055d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
