name       : ksmtp
version    : 19.04.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/ksmtp-19.04.1.tar.xz : 965f5f1c44cd64f9899ff5919372fe449e0f8b63e492f566017c9b8d5eb324bb
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
