name       : ksmtp
version    : 19.12.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/ksmtp-19.12.0.tar.xz : 157c6112dfd2aaafe991e17bfd115a74721526642d6e52241d83142f541269a2
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
