name       : ksmtp
version    : 20.08.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/ksmtp-20.08.0.tar.xz : 3fe08534bdb7037a8fd9a8c1a37456abe80252994232cfe31c368dcdc3c328c2
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
