name       : ksmtp
version    : 17.12.3
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/ksmtp-17.12.3.tar.xz : 2be5b3e48699949edc5c26c8ba772ffa35f3e5598f065e1108b1c71fb3149ab7
license    : LGPL-2.1
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
