name       : ksmtp
version    : 18.04.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/ksmtp-18.04.1.tar.xz : 8366b738e328b7a47741254d1b72b3dad84df28f9170d151d0e8c0ada362ae46
license    : LGPL-2.1
component  : programming.library
optimize   : lto
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
