name       : ksmtp
version    : 21.08.2
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/ksmtp-21.08.2.tar.xz : d00faa4d3d30ccb6e3007c578681403cf7da6fbfcf691b78a25e6d8e87886d21
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
