name       : ksmtp
version    : 19.08.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/ksmtp-19.08.1.tar.xz : 71401abcbb6aedd2845c84bca65f77297722b3414f4d4caeaa6ac6b8f2edc46c
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
