name       : ksmtp
version    : 18.12.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/ksmtp-18.12.0.tar.xz : c40702cc9df0e210765cba6f7904b2f4209806911ce05e139939107c68c558b1
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
