name       : ksmtp
version    : 21.04.3
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/ksmtp-21.04.3.tar.xz : 015ace6969a68fcfc0cbee227f8e386be2e4125a56b265f03d03e34a6232b508
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
