name       : ksmtp
version    : 21.04.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/ksmtp-21.04.0.tar.xz : c557835c9ee292f23f82f4aa67d6516cc9012ad529b5c1d8ea1931f07c64c456
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
