name       : ksmtp
version    : 20.04.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/ksmtp-20.04.1.tar.xz : 1daebe85fddbab20a6891d6fea6d57fd6b6314f665aac81b1eac81ba2254caf7
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
