name       : ksmtp
version    : 17.12.1
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/ksmtp-17.12.1.tar.xz : 425763fa5d2d78a788362349f4aceeeb6fd085107d94858e91f25fe11dbfc087
license    : LGPL-2.1
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
