name       : ksmtp
version    : 18.08.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/ksmtp-18.08.3.tar.xz : 03a57e363daab7d89737c00aa51805f37396edcbab96b375e24cf1cc30e3f853
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
