name       : ksmtp
version    : 22.04.2
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/ksmtp-22.04.2.tar.xz : 76321620c7aa0c1b1e858145a9d47723d419d9e5e96ba6518604f00e1acc7c00
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
