name       : ksmtp
version    : 21.12.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/ksmtp-21.12.1.tar.xz : 981273efff8f47aaca1672aabdc0f40d5cbfd5d730d35dd25758d58bdd320c89
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
